import json
questions = {
    "Spm1": "Hvor interessert er du i politikk generelt?", 
    "Spm2": "Hvor ofte diskuterte du valget med familie, venner eller bekjente foran valget i år?", 
    "Spm3": "Hvor mye brydde du deg personlig om hvilket parti eller hvilke partier som vant valget nå i høst?", 
    "spm6_1": "Hvilket parti synes du har best skole- og utdanningspolitikk?",
    "spm6_2": "Hvilket parti synes du har best skatte- og avgiftspolitikk?",
    "spm6_3": "Hvilket parti synes du har best innvandringspolitikk?",
    "spm6_4": "Hvilket parti synes du har best klima- og miljøpolitikk?",
    "spm6_5": "Hvilket parti synes du har best politikk for eldreomsorg?",
    "spm6_6": "Hvilket parti synes du har best samferdselspolitikk?",
    "spm6_7": "Hvilket parti synes du har best barne- og familiepolitikk?",
    "spm6_8": "Hvilket parti synes du har best distriktspolitikk?",
    "spm6_9": "Hvilket parti synes du har best helsepolitikk?",
    "spm6_10": "Hvilket parti synes du har best sysselsettingspolitikk?",
    "spm6_11": "Hvilket parti synes du har best økonomisk fordelingspolitikk?",
    "spm17_1": "Hvor vil du plassere de politiske partiene på en skala fra 0 til 10, der 0 betyr at du sterkt misliker og 10 betyr at du liker partiet svært godt\nKristelig Folkeparti",
    "spm17_2": "Hvor vil du plassere de politiske partiene på en skala fra 0 til 10, der 0 betyr at du sterkt misliker og 10 betyr at du liker partiet svært godt\nVenstre",
    "spm17_3": "Hvor vil du plassere de politiske partiene på en skala fra 0 til 10, der 0 betyr at du sterkt misliker og 10 betyr at du liker partiet svært godt\nSenterpartiet",
    "spm17_4": "Hvor vil du plassere de politiske partiene på en skala fra 0 til 10, der 0 betyr at du sterkt misliker og 10 betyr at du liker partiet svært godt\nSosialistisk Venstreparti",
    "spm17_5": "Hvor vil du plassere de politiske partiene på en skala fra 0 til 10, der 0 betyr at du sterkt misliker og 10 betyr at du liker partiet svært godt\nHøyre",
    "spm17_6": "Hvor vil du plassere de politiske partiene på en skala fra 0 til 10, der 0 betyr at du sterkt misliker og 10 betyr at du liker partiet svært godt\nArbeiderpartiet",
    "spm17_7": "Hvor vil du plassere de politiske partiene på en skala fra 0 til 10, der 0 betyr at du sterkt misliker og 10 betyr at du liker partiet svært godt\nFremskrittspartiet",
    "spm17_8": "Hvor vil du plassere de politiske partiene på en skala fra 0 til 10, der 0 betyr at du sterkt misliker og 10 betyr at du liker partiet svært godt\nRødt",
    "spm17_9": "Hvor vil du plassere de politiske partiene på en skala fra 0 til 10, der 0 betyr at du sterkt misliker og 10 betyr at du liker partiet svært godt\nMiljøpartiet",
    "spm19_1": "I politikken snakkes det om venstresiden og høyresiden. Hvor vil du plassere de politiske partiene på en skala fra 0 til 10, der 0 betyr venstresiden og 10 betyr høyresiden?\nSenterpartiet",
    "spm19_2": "I politikken snakkes det om venstresiden og høyresiden. Hvor vil du plassere de politiske partiene på en skala fra 0 til 10, der 0 betyr venstresiden og 10 betyr høyresiden?\nFremskrittspartiet",
    "spm19_3": "I politikken snakkes det om venstresiden og høyresiden. Hvor vil du plassere de politiske partiene på en skala fra 0 til 10, der 0 betyr venstresiden og 10 betyr høyresiden?\nVenstre",
    "spm19_4": "I politikken snakkes det om venstresiden og høyresiden. Hvor vil du plassere de politiske partiene på en skala fra 0 til 10, der 0 betyr venstresiden og 10 betyr høyresiden?\nArbeiderpartiet",
    "spm19_5": "I politikken snakkes det om venstresiden og høyresiden. Hvor vil du plassere de politiske partiene på en skala fra 0 til 10, der 0 betyr venstresiden og 10 betyr høyresiden?\nHøyre",
    "spm19_6": "I politikken snakkes det om venstresiden og høyresiden. Hvor vil du plassere de politiske partiene på en skala fra 0 til 10, der 0 betyr venstresiden og 10 betyr høyresiden?\nKristelig Folkeparti",
    "spm19_7": "I politikken snakkes det om venstresiden og høyresiden. Hvor vil du plassere de politiske partiene på en skala fra 0 til 10, der 0 betyr venstresiden og 10 betyr høyresiden?\nSosialistisk Venstreparti",
    "spm19_8": "I politikken snakkes det om venstresiden og høyresiden. Hvor vil du plassere de politiske partiene på en skala fra 0 til 10, der 0 betyr venstresiden og 10 betyr høyresiden?\nRødt",
    "spm19_9": "I politikken snakkes det om venstresiden og høyresiden. Hvor vil du plassere de politiske partiene på en skala fra 0 til 10, der 0 betyr venstresiden og 10 betyr høyresiden?\nMiljøpartiet de Grønne",
    "Spm5a": "Hvor enig, eller uenig er du i disse påstandene?\nEØS-avtalen bør sies opp",
    "Spm5b": "Hvor enig, eller uenig er du i disse påstandene?\nDet har stort sett vært riktig å slå sammen kommuner",
    "Spm5c": "Hvor enig, eller uenig er du i disse påstandene?\nOffentlige tjenester vil ikke bli noe bedre med færre og større kommuner",
    "Spm5d": "Hvor enig, eller uenig er du i disse påstandene?\nDet har stort sett vært riktig å slå sammen fylker",
    "Spm5e": "Hvor enig, eller uenig er du i disse påstandene?\nI den nåværende økonomiske situasjon er det rom for betydelige lettelser i skatter og avgifter",
    "Spm5f": "Hvor enig, eller uenig er du i disse påstandene?\nDet bør bli tillatt å bruke surrogatmor for å bære frem et barn i Norge",
    "Spm5g": "Hvor enig, eller uenig er du i disse påstandene?\nUlvebestanden i Norge bør reduseres",
    "Spm5h": "Hvor enig, eller uenig er du i disse påstandene?\nMange offentlige aktiviteter kunne blitt utført både bedre og billigere, hvis de ble overlatt til private",
    "Spm5i": "Hvor enig, eller uenig er du i disse påstandene?\nForskjellene i nordmenns økonomiske evne er fortsatt så store at myndighetene må se det som en hovedoppgave å minske dem",
    "Spm7a": "Hvor enig, eller uenig er du i disse påstandene?\nPolitikken er ofte så innviklet at alminnelige folk ikke kan sette seg inn i hva den dreier seg om",
    "Spm7b": "Hvor enig, eller uenig er du i disse påstandene?\nFormuesskatten bør avskaffes",
    "Spm7c": "Hvor enig, eller uenig er du i disse påstandene?\nVi bør tillate kommersielle privatskoler",
    "Spm7d": "Hvor enig, eller uenig er du i disse påstandene?\nPolitikere og byråkrater i Oslo forstår lite av det som skjer i distrikts-Norge",
    "Spm7e": "Hvor enig, eller uenig er du i disse påstandene?\nDet er viktig at vi underskriver internasjonale avtaler selv om det begrenser norske myndigheters handlefrihet",
    "Spm7f": "Hvor enig, eller uenig er du i disse påstandene?\nFor å løse aktuelle samfunnsspørsmål kan vi bruke mye mer av oljefondet enn i dag",
    "Spm7g": "Hvor enig, eller uenig er du i disse påstandene?\nGlobalisering er helt nødvendig for å sikre økonomisk vekst",
    "Spm23a": "Hvor enig, eller uenig er du i disse påstandene?\nNorge bør forby leting etter mer olje og gass",
    "Spm23b": "Hvor enig, eller uenig er du i disse påstandene?\nNorske politikere bør ta hensyn til andre europeiske regjeringers synspunkter før de tar sine beslutninger",
    "Spm23c": "Hvor enig, eller uenig er du i disse påstandene?\nDet er viktigere å bygge ut ren energi enn å bevare urørt natur",
    "Spm23d": "Hvor enig, eller uenig er du i disse påstandene?\nFlyktninger og innvandrere bør ha samme rett til sosialhjelp som nordmenn, selv om de ikke er norske statsborgere",
    "Spm23e": "Hvor enig, eller uenig er du i disse påstandene?\nVesteuropeiske og muslimske måter å leve på er uforenlige",
    "Spm23f": "Hvor enig, eller uenig er du i disse påstandene?\nInnvandrere er i hovedsak bra for norsk økonom",
    "Spm23h": "Hvor enig, eller uenig er du i disse påstandene?\nDet legges altfor lite vekt på miljøvern i dagens Norge",
    "Spm31a": "Hvor enig eller uenig er du i følgende påstander:\nEn god leder bør være streng mot sine underordnede hvis han/hun vil sette seg i respekt",
    "Spm31b": "Hvor enig eller uenig er du i følgende påstander:\nDet viktigste barn bør lære er lydighet og respekt for sine foresatte",
    "Spm31c": "Hvor enig eller uenig er du i følgende påstander:\nDet vi trenger mest her i landet, mer enn lover og programmer, er noen få, uselviske og myndige ledere som folket trygt kan følge",
    "Spm48a": "Hvor enig eller uenig er du i følgende påstander:\nKlimaendringene er i hovedsak menneskeskapt",
    "Spm48b": "Hvor enig eller uenig er du i følgende påstander:\nForby bruk av privatbil i indre byområder",
    "Spm48c": "Hvor enig eller uenig er du i følgende påstander:\nVi bør satse mer på utbygging av vindkraft",
    "Spm48d": "Hvor enig eller uenig er du i følgende påstander:\nVi bør innføre mye strengere klimatiltak, selv om det fører til lavere levestandard",
    "Spm48e": "Hvor enig eller uenig er du i følgende påstander:\nVi bør satse på et samfunn med høy økonomisk vekst og produktivitet",
    "Spm48f": "Hvor enig eller uenig er du i følgende påstander:\nInnvandring utgjør en alvorlig trussel mot vår nasjonale egenart",
    "Spm48g": "Hvor enig eller uenig er du i følgende påstander:\nI dårlige tider bør vi først og fremst sørge for arbeid til nordmenn",
    "Spm51a": "Hvor enig eller uenig er du i følgende påstander?\nOrdningen med kontantstøtte bør fjernes",
    "Spm51b": "Hvor enig eller uenig er du i følgende påstander?\nDet bør være samme mulighet til adopsjon for homofile som for heterofile",
    "Spm51c": "Hvor enig eller uenig er du i følgende påstander?\nFlere statlige virksomheter bør flyttes ut i distriktene",
    "Spm51d": "Hvor enig eller uenig er du i følgende påstander?\nVi bør tillate aktiv dødshjelp",
    "Spm51e": "Hvor enig eller uenig er du i følgende påstander?\nVi bør redusere den statlige kontrollen over privat næringsliv",
    "Spm51f": "Hvor enig eller uenig er du i følgende påstander?\nVi bør satse på et samfunn der kristne verdier spiller en større rolle",
    "Spm51g": "Hvor enig eller uenig er du i følgende påstander?\nVi bør satse på et samfunn med mer internasjonal orientering og med mindre vekt på grenser mellom folk og land"}

with open('combined_questions.json', 'r', encoding="utf-8") as f:
    question_dict = json.load(f)

for k,v in questions.items():
    question_dict[k]["question"] = v

with open('combined_questions.json', 'w', encoding="utf-8") as f:
    json.dump(question_dict, f,ensure_ascii=False)